/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CariBuku.java
 *
 * Created on Nov 29, 2013, 5:08:27 PM
 */
package perpustakaan.user;
import com.sun.org.apache.bcel.internal.generic.TABLESWITCH;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author HerdiandKun
 */
public class CariBuku extends javax.swing.JFrame {
Connection con;
Statement st;
ResultSet rs;
private Object[][] dataTable = null;
private String[] header = {"ID Buku","Judul","Author","Penerbit","Rak","Stock"};
    /** Creates new form CariBuku */
    public CariBuku() {
        initComponents();
        open_db();
    }
private void open_db()
    {
        try{
        Class.forName("com.mysql.jdbc.Driver");
        con=DriverManager.getConnection("jdbc:mysql://localhost:3306/perpustakaan","root","");
        
        }catch(Exception e){
        System.out.println("Error : "+e);
        }
    }
private void baca_data(){
        try{
                ResultSetMetaData meta = rs.getMetaData();
                int col = meta.getColumnCount();
                int baris = 0;
                while(rs.next()) {
                    baris = rs.getRow();
                }
                dataTable = new Object[baris][col];
                int x = 0;
                rs.beforeFirst();
                while(rs.next()) {
                    dataTable[x][0] = rs.getString(1);
                    dataTable[x][1] = rs.getString(2);
                    dataTable[x][2] = rs.getString(3);
                    dataTable[x][3] = rs.getString(4);
                    dataTable[x][4] = rs.getString(5);
                    dataTable[x][5] = rs.getString(6);
                    x++;
                }
                tblbuku.setModel(new DefaultTableModel(dataTable,header));
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        lbltipepencarian = new javax.swing.JLabel();
        txtCari = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblbuku = new javax.swing.JTable();
        btnKembali = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setFont(new java.awt.Font("Comic Sans MS", 0, 36));
        jComboBox1.setForeground(new java.awt.Color(0, 153, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Author", "Judul Buku", "Penerbit" }));
        jComboBox1.setBorder(null);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 60, 350, 50));

        lbltipepencarian.setFont(new java.awt.Font("Comic Sans MS", 0, 36));
        lbltipepencarian.setForeground(new java.awt.Color(0, 153, 255));
        lbltipepencarian.setText("Author");
        getContentPane().add(lbltipepencarian, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 150, -1, -1));

        txtCari.setFont(new java.awt.Font("Comic Sans MS", 0, 36));
        txtCari.setForeground(new java.awt.Color(0, 153, 255));
        txtCari.setBorder(null);
        txtCari.setCaretColor(new java.awt.Color(0, 153, 255));
        txtCari.setDisabledTextColor(new java.awt.Color(0, 153, 255));
        getContentPane().add(txtCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 140, 350, 60));

        btnSubmit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/buttonsearch2.png"))); // NOI18N
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        getContentPane().add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 220, 70, 70));

        tblbuku.setFont(new java.awt.Font("Comic Sans MS", 0, 18));
        tblbuku.setForeground(new java.awt.Color(0, 153, 204));
        tblbuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Buku", "Judul Buku", "Author", "Penerbit", "Rak", "Stock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblbuku.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(tblbuku);
        tblbuku.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 1230, 94));

        btnKembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/kembali_button.png"))); // NOI18N
        btnKembali.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnKembali.setContentAreaFilled(false);
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });
        getContentPane().add(btnKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 220, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Master_cari_buku.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed

    if(lbltipepencarian.getText().equalsIgnoreCase("Author")){
try{
    st = con.createStatement();
    rs = st.executeQuery("select * from buku where Author = '"+txtCari.getText()+"'");
    baca_data();
}catch(SQLException e){
    JOptionPane.showMessageDialog(null, e);
    }
}
    else if(lbltipepencarian.getText().equalsIgnoreCase("Judul Buku")){
try{
    st = con.createStatement();
    rs = st.executeQuery("select * from buku where Judul = '"+txtCari.getText()+"'");
    baca_data();
}catch(SQLException e){
    JOptionPane.showMessageDialog(null, e);
    }
    }
    else if(lbltipepencarian.getText().equalsIgnoreCase("Penerbit")){
try{
    st = con.createStatement();
    rs = st.executeQuery("select * from buku where Penerbit = '"+txtCari.getText()+"'");
    baca_data();
}catch(SQLException e){
    JOptionPane.showMessageDialog(null, e);
    }
}
    // TODO add your handling code here:
}//GEN-LAST:event_btnSubmitActionPerformed

private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
lbltipepencarian.setText(jComboBox1.getSelectedItem()+"");// TODO add your handling code here:
}//GEN-LAST:event_jComboBox1ActionPerformed

private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
Interface1 face = new Interface1();
face.setVisible(true);
this.dispose();
// TODO add your handling code here:
}//GEN-LAST:event_btnKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CariBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CariBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CariBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CariBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new CariBuku().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbltipepencarian;
    private javax.swing.JTable tblbuku;
    private javax.swing.JTextField txtCari;
    // End of variables declaration//GEN-END:variables
}
