/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CekAnggota.java
 *
 * Created on Dec 10, 2013, 8:38:13 AM
 */
package perpustakaan.user;
import java.sql.*;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import java.util.List;
import app.data.student;
/**
 *
 * @author HerdiandKun
 */
public class CekAnggota extends javax.swing.JFrame {
    
    Connection cn=null;
    ResultSet RsUser;
    Statement stm;
    /** Creates new form CekAnggota */
    public CekAnggota() {
    
        initComponents();
        open_db();
    }
  private void open_db()
    {
        try{
        Class.forName("com.mysql.jdbc.Driver");
        cn=DriverManager.getConnection("jdbc:mysql://localhost:3306/perpustakaan","root","");
        
        }catch(Exception e){
        System.out.println("Error : "+e);
        }
    }  
  private void baca()
  {
      try{
    stm = cn.createStatement();
    RsUser = stm.executeQuery("select * from student");
    if(RsUser.next())
    {
     //String nohp=Integer.toString((Integer) RsUser.getString(7));
     textData.setText("ID\t: "+RsUser.getString(1)+"\nNIM\t: "+RsUser.getString(2)+"\nNama\t: "+RsUser.getString(3)+
                    "\nPK\t: "+RsUser.getString(4)+"\nAlamat\t: "+RsUser.getString(5)+"\nMasa Aktif\t: "+RsUser.getString(6)+
                    "\nNo HP\t: "+RsUser.getString(7)
                    );
    }

    } catch(SQLException e){
    JOptionPane.showMessageDialog(null, e);
    }
  }
          /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNIM = new javax.swing.JLabel();
        txtNIM = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textData = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNIM.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        lblNIM.setForeground(new java.awt.Color(0, 153, 204));
        lblNIM.setText("Masukan NIM");
        getContentPane().add(lblNIM, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 260, 50));

        txtNIM.setFont(new java.awt.Font("Bookman Old Style", 1, 28));
        txtNIM.setForeground(new java.awt.Color(0, 102, 255));
        txtNIM.setCaretColor(new java.awt.Color(0, 255, 255));
        txtNIM.setSelectionColor(new java.awt.Color(0, 255, 255));
        getContentPane().add(txtNIM, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 500, 60));

        btnSubmit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/login_button.png"))); // NOI18N
        btnSubmit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSubmit.setContentAreaFilled(false);
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        getContentPane().add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 397, 70, -1));

        btnKembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/kembali_button.png"))); // NOI18N
        btnKembali.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnKembali.setContentAreaFilled(false);
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });
        getContentPane().add(btnKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 680, -1, -1));

        textData.setColumns(20);
        textData.setFont(new java.awt.Font("Bookman Old Style", 0, 14));
        textData.setForeground(new java.awt.Color(0, 153, 204));
        textData.setRows(5);
        jScrollPane1.setViewportView(textData);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 400, 680, 270));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/cek_anggota_master2.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
try{
    stm = cn.createStatement();
    RsUser = stm.executeQuery("select * from student where Nim = '"+txtNIM.getText()+"'");
    if(RsUser.next())
    {
     //String nohp=Integer.toString((Integer) RsUser.getString(7));
     textData.setText("ID\t: "+RsUser.getString(1)+"\nNIM\t: "+RsUser.getString(2)+"\nNama\t: "+RsUser.getString(3)+
                    "\nPK\t: "+RsUser.getString(4)+"\nAlamat\t: "+RsUser.getString(5)+"\nMasa Aktif\t: "+RsUser.getString(6)+
                    "\nNo HP\t: "+RsUser.getString(7)
                    );
    }
    else if(txtNIM.getText().equals(""))
    {
        JOptionPane.showMessageDialog(this, "Nim Kosong", "Information", JOptionPane.INFORMATION_MESSAGE);
    }
    else {
        textData.setText("\n\n\n\n\n\n\n\n\n\n Nim Yang Anda Masukan Belum Terdaftar\n anda "
                + "tidak dapat masuk perpustakaan");
    }//String nohp=Integer.toString((Integer) RsUser.getString(7));   
    } catch(SQLException e){
    JOptionPane.showMessageDialog(null, e);
    }
textData.setEditable(false);
// TODO add your handling code here:
}//GEN-LAST:event_btnSubmitActionPerformed

private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
Interface1 face = new Interface1();
face.setVisible(true);
this.dispose();
// TODO add your handling code here:
}//GEN-LAST:event_btnKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CekAnggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CekAnggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CekAnggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CekAnggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new CekAnggota().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNIM;
    private javax.swing.JTextArea textData;
    private javax.swing.JTextField txtNIM;
    // End of variables declaration//GEN-END:variables

 
}
