/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*port 
 * Interface1.java
 *
 * Created on Nov 29, 2013, 4:49:17 PM
 */
package perpustakaan.user;
import perpustakaan.user.CekAnggota;
import perpustakaan.user.CariBuku;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author HerdiandKun
 */
public class Interface1 extends javax.swing.JFrame {

    /** Creates new form Interface1 */
    public Interface1() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btncari = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btncek = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("INFORMASI PERPUSTAKAAN");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btncari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/caribuku.png"))); // NOI18N
        btncari.setBorder(null);
        btncari.setBorderPainted(false);
        btncari.setContentAreaFilled(false);
        btncari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncariActionPerformed(evt);
            }
        });
        getContentPane().add(btncari, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 570, 310, 100));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(732, 185, -1, -1));

        btncek.setBackground(new java.awt.Color(255, 255, 255));
        btncek.setForeground(new java.awt.Color(255, 255, 255));
        btncek.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/cek_anggota2.png"))); // NOI18N
        btncek.setBorder(null);
        btncek.setBorderPainted(false);
        btncek.setContentAreaFilled(false);
        btncek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncekActionPerformed(evt);
            }
        });
        getContentPane().add(btncek, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 570, 270, 100));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/interface_awal_master2.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncariActionPerformed
        CariBuku cari = new CariBuku();
        cari.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btncariActionPerformed

    private void btncekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncekActionPerformed
        CekAnggota cek = new CekAnggota();
        cek.setVisible(true);// TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btncekActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Interface1().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncari;
    private javax.swing.JButton btncek;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
