package perpustakaan.admin;
import app.data.ConnectionUtilities;
import java.sql.*;
import perpustakaan.user.CekAnggota;
import app.data.student;
import app.data.studentManager;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import javax.swing.JDialog;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.swing.JRViewer;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DEA
 */
public class Cek_Anggota extends javax.swing.JFrame {
Connection con;
Statement st;
ResultSet rs;
private Object[][] dataTable = null;
private String[] header = {"ID","NIM","Nama","PK","Alamat","Masa Aktof","No HP"};
    /**
     * Creates new form Cek_Anggota
     */
    public Cek_Anggota() {  
        initComponents();
        open_db();
        
    }
private void open_db()
    {
        try{
        Class.forName("com.mysql.jdbc.Driver");
        con=DriverManager.getConnection("jdbc:mysql://localhost:3306/perpustakaan","root","");
         st = con.createStatement();
         rs = st.executeQuery("select * from student");
         baca_data();
        }catch(Exception e){
        System.out.println("Error : "+e);
        }
    }
private void baca_data(){
        try{
                ResultSetMetaData meta = rs.getMetaData();
                int col = meta.getColumnCount();
                int baris = 0;
                while(rs.next()) {
                    baris = rs.getRow();
                }
                dataTable = new Object[baris][col];
                int x = 0;
                rs.beforeFirst();
                while(rs.next()) {
                    dataTable[x][0] = rs.getString(1);
                    dataTable[x][1] = rs.getString(2);
                    dataTable[x][2] = rs.getString(3);
                    dataTable[x][3] = rs.getString(4);
                    dataTable[x][4] = rs.getString(5);
                    dataTable[x][5] = rs.getString(6);
                    dataTable[x][6] = rs.getString(7);
                    x++;
                }
                TblAnggota.setModel(new DefaultTableModel(dataTable,header));
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnHome = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblAnggota = new javax.swing.JTable();
        txtcari = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHome.setText("HOME");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        getContentPane().add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(1514, 1021, -1, -1));

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 24));
        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setText("HASIL PENCARIAN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 360, -1, -1));

        TblAnggota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID_Anggota", "Nama", "NIM", "PK", "Masa Aktif", "Alamat", "No_HP"
            }
        ));
        jScrollPane1.setViewportView(TblAnggota);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 1360, 170));

        txtcari.setBorder(null);
        getContentPane().add(txtcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 270, 290, 30));

        btnSearch.setFont(new java.awt.Font("Consolas", 1, 24));
        btnSearch.setForeground(new java.awt.Color(0, 153, 255));
        btnSearch.setText("CARI");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 257, 90, 50));

        jButton1.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 204));
        jButton1.setText("Kembali");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 30, -1, -1));

        jButton2.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 153, 204));
        jButton2.setText("Cetak Laporan");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 30, -1, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/master_pengecekan_keanggotaan.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
    try{
    st = con.createStatement();
    rs = st.executeQuery("select * from student where Nim = '"+txtcari.getText()+"'");
     baca_data();
    if(txtcari.getText().equals(""))
    {
        JOptionPane.showMessageDialog(this, "Nim Kosong", "Information", JOptionPane.INFORMATION_MESSAGE);
        open_db();
    }
    //String nohp=Integer.toString((Integer) RsUser.getString(7));   
    } catch(SQLException e){
    JOptionPane.showMessageDialog(null, e);
    }// TODO add your handling code here:
}//GEN-LAST:event_btnSearchActionPerformed

private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
new halamanutama().setVisible(true);
dispose();// TODO add your handling code here:
}//GEN-LAST:event_btnHomeActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
try{
        String stream = "H:/Report Perpustakaan/anggota.jrxml";
        
        JasperReport jasperReport = JasperCompileManager.compileReport(stream);
        JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, null, ConnectionUtilities.getConnection());
        JRViewer aViewer = new JRViewer(jasperPrint);
        
        JDialog viewer = new JDialog();
        viewer.setTitle(".: Jasper Report :.");
        viewer.setAlwaysOnTop(true);
        viewer.getContentPane().add(aViewer);
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        viewer.setBounds(0,0,screenSize.width, screenSize.height);
        viewer.setVisible(true);
        
    }catch(JRException ex){
        Logger.getLogger(ManipulasiAnggota.class.getName()).log(Level.SEVERE, null, ex);
    }// TODO add your handling code here:
}//GEN-LAST:event_jButton2ActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
new halamanutama().setVisible(true);
dispose();// TODO add your handling code here:
}//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cek_Anggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cek_Anggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cek_Anggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cek_Anggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cek_Anggota().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TblAnggota;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtcari;
    // End of variables declaration//GEN-END:variables
}
