package perpustakaan.admin;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DEA
 */
public class halamanutama extends javax.swing.JFrame {

    /**
     * Creates new form halamanutama
     */
    public halamanutama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPeminjaman = new javax.swing.JButton();
        btnPengembalian = new javax.swing.JButton();
        btncekanggota = new javax.swing.JButton();
        btncekbuku = new javax.swing.JToggleButton();
        btnManpulasiAnggota = new javax.swing.JButton();
        btnManipulasiBuku = new javax.swing.JButton();
        Logout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPeminjaman.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        btnPeminjaman.setForeground(new java.awt.Color(102, 204, 255));
        btnPeminjaman.setText("Peminjaman");
        btnPeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeminjamanActionPerformed(evt);
            }
        });
        getContentPane().add(btnPeminjaman, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 370, 270, -1));

        btnPengembalian.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        btnPengembalian.setForeground(new java.awt.Color(102, 204, 255));
        btnPengembalian.setText("Pengembalian");
        btnPengembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPengembalianActionPerformed(evt);
            }
        });
        getContentPane().add(btnPengembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 420, 270, -1));

        btncekanggota.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        btncekanggota.setForeground(new java.awt.Color(102, 204, 255));
        btncekanggota.setText("Cek Anggota");
        btncekanggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncekanggotaActionPerformed(evt);
            }
        });
        getContentPane().add(btncekanggota, new org.netbeans.lib.awtextra.AbsoluteConstraints(535, 520, 260, -1));

        btncekbuku.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        btncekbuku.setForeground(new java.awt.Color(102, 204, 255));
        btncekbuku.setText("Cek Buku");
        btncekbuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncekbukuActionPerformed(evt);
            }
        });
        getContentPane().add(btncekbuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(525, 470, 280, -1));

        btnManpulasiAnggota.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        btnManpulasiAnggota.setForeground(new java.awt.Color(102, 204, 255));
        btnManpulasiAnggota.setText("Manipulasi Anggota");
        btnManpulasiAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManpulasiAnggotaActionPerformed(evt);
            }
        });
        getContentPane().add(btnManpulasiAnggota, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, -1, -1));

        btnManipulasiBuku.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        btnManipulasiBuku.setForeground(new java.awt.Color(102, 204, 255));
        btnManipulasiBuku.setText("Manipulasi Buku");
        btnManipulasiBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManipulasiBukuActionPerformed(evt);
            }
        });
        getContentPane().add(btnManipulasiBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, 270, -1));

        Logout.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        Logout.setForeground(new java.awt.Color(102, 204, 255));
        Logout.setText("Keluar");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        getContentPane().add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 220, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/master_menu_admin_1.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnPeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeminjamanActionPerformed
new Peminjaman().setVisible(true);
dispose();// TODO add your handling code here:
}//GEN-LAST:event_btnPeminjamanActionPerformed

private void btnPengembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPengembalianActionPerformed
new Pengembalian().setVisible(true);
dispose();// TODO add your handling code here:
}//GEN-LAST:event_btnPengembalianActionPerformed

private void btncekanggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncekanggotaActionPerformed
new Cek_Anggota().setVisible(true);
dispose();// TODO add your handling code here:
}//GEN-LAST:event_btncekanggotaActionPerformed

private void btncekbukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncekbukuActionPerformed
new CekBuku().setVisible(true);
dispose();// TODO add your handling code here:
}//GEN-LAST:event_btncekbukuActionPerformed

private void btnManpulasiAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManpulasiAnggotaActionPerformed
new ManipulasiAnggota().setVisible(true);
dispose();// TODO add your handling code here:
}//GEN-LAST:event_btnManpulasiAnggotaActionPerformed

private void btnManipulasiBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManipulasiBukuActionPerformed
new ManipulasiBuku().setVisible(true);
dispose();// TODO add your handling code here:
}//GEN-LAST:event_btnManipulasiBukuActionPerformed

private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
new login().setVisible(true);
dispose();// TODO add your handling code here:
}//GEN-LAST:event_LogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(halamanutama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(halamanutama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(halamanutama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(halamanutama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new halamanutama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Logout;
    private javax.swing.JButton btnManipulasiBuku;
    private javax.swing.JButton btnManpulasiAnggota;
    private javax.swing.JButton btnPeminjaman;
    private javax.swing.JButton btnPengembalian;
    private javax.swing.JButton btncekanggota;
    private javax.swing.JToggleButton btncekbuku;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
