


/*
 * login.java
 *
 * 
 */
package perpustakaan.admin;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author HerdiandKun
 */
public class login extends javax.swing.JFrame {
    Connection cn=null;
    ResultSet RsUser;
    Statement stm;
    /** Creates new form login */
    public login() {
        initComponents();
        open_db();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUserId = new javax.swing.JTextField();
        cmdOk = new javax.swing.JButton();
        cmdBatal = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();
        btnDaftar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 204));
        jLabel1.setText("ID ADMIN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, 180, 40));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 24));
        jLabel2.setForeground(new java.awt.Color(0, 153, 204));
        jLabel2.setText("KATA SANDI");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 300, -1, -1));

        txtUserId.setFont(new java.awt.Font("Comic Sans MS", 1, 18));
        txtUserId.setForeground(new java.awt.Color(0, 153, 204));
        txtUserId.setBorder(null);
        txtUserId.setCaretColor(new java.awt.Color(0, 153, 204));
        txtUserId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserIdActionPerformed(evt);
            }
        });
        getContentPane().add(txtUserId, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, 410, 30));

        cmdOk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/login_button.png"))); // NOI18N
        cmdOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdOkActionPerformed(evt);
            }
        });
        getContentPane().add(cmdOk, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 430, 80, -1));

        cmdBatal.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        cmdBatal.setForeground(new java.awt.Color(0, 153, 204));
        cmdBatal.setText("KELUAR");
        cmdBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBatalActionPerformed(evt);
            }
        });
        getContentPane().add(cmdBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 570, 160, 40));

        txtPassword.setFont(new java.awt.Font("Comic Sans MS", 1, 24));
        txtPassword.setForeground(new java.awt.Color(0, 153, 204));
        txtPassword.setBorder(null);
        txtPassword.setCaretColor(new java.awt.Color(0, 153, 204));
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 360, 410, 20));

        btnDaftar.setFont(new java.awt.Font("Comic Sans MS", 1, 14));
        btnDaftar.setForeground(new java.awt.Color(0, 153, 204));
        btnDaftar.setText("TAMBAH ADMIN");
        btnDaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaftarActionPerformed(evt);
            }
        });
        getContentPane().add(btnDaftar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 520, 160, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Login_admin_fix.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void open_db()
    {
        try{
        Class.forName("com.mysql.jdbc.Driver");
        cn=DriverManager.getConnection("jdbc:mysql://localhost:3306/perpustakaan","root","");
        
        }catch(Exception e){
        System.out.println("Error : "+e);
        }
    }
private void txtUserIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserIdActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_txtUserIdActionPerformed

private void cmdOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdOkActionPerformed
// TODO add your handling code here:
    try{
    char[] input=txtPassword.getPassword();
    String password;
    password = new String(txtPassword.getPassword());
    stm = cn.createStatement();
    RsUser = stm.executeQuery("select * from admin where user_id = '"+
    txtUserId.getText()+"' and password='"+password+"'");
    int baris=0;
    while(RsUser.next()){
    baris = RsUser.getRow();
    }
    if(baris==1)
    {
    JOptionPane.showMessageDialog(null, "User dan Password Cocok");
    new halamanutama().setVisible(true);
    this.dispose();
    //System.exit(0);
    }
    else
    {
    JOptionPane.showMessageDialog(null, "User atau Password tdk Cocok -> "+
            txtUserId.getText() +" --> "+password);
    }
    }catch(SQLException e){
    JOptionPane.showMessageDialog(null, e);
    }
}//GEN-LAST:event_cmdOkActionPerformed

private void cmdBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBatalActionPerformed
// TODO add your handling code here:
    System.exit(0);
 
}//GEN-LAST:event_cmdBatalActionPerformed

private void btnDaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaftarActionPerformed
DaftarAdmin da = new DaftarAdmin();
da.setVisible(true);
dispose();
// TODO add your handling code here:
}//GEN-LAST:event_btnDaftarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new login().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDaftar;
    private javax.swing.JButton cmdBatal;
    private javax.swing.JButton cmdOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUserId;
    // End of variables declaration//GEN-END:variables
}
