/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ManipulasiAnggota.java
 *
 * Created on Dec 12, 2013, 7:58:46 PM
 */
package perpustakaan.admin;
import app.data.studentManager;
import app.data.student;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.lang.ArrayIndexOutOfBoundsException;
import java.text.SimpleDateFormat;

/**
 *
 * @author HerdiandKun
 */
public class ManipulasiAnggota extends javax.swing.JFrame {
Connection con;
Statement st;
ResultSet rs;
private Object[][] dataTable = null;
private String[] header = {"ID","NIM","Nama","PK","Alamat","Masa Aktif","No HP"};
Date dt = new Date();
    SimpleDateFormat df = new SimpleDateFormat("dd-MM-yyyy");
    com.mysql.jdbc.PreparedStatement pst;
    /** Creates new form ManipulasiAnggota */
    public ManipulasiAnggota() {
        initComponents();
        open_db();
        GregorianCalendar now = new GregorianCalendar();
        
        Calendar cal = Calendar.getInstance();
        txtxMasa.setText(cal.get(Calendar.DATE) + "-"+cal.get(Calendar.MONTH)+1 +"-"+(cal.get(Calendar.YEAR)+1));
       }
    
    
    /**
     * Creates new form Cek_Anggota
     */
private void setField()
{ int row=TblAnggota.getSelectedRow();
        txtID.setText((String)TblAnggota.getValueAt(row,0));
        txtNim.setText((String)TblAnggota.getValueAt(row,1));
        txtNama.setText((String)TblAnggota.getValueAt(row,2));
        txtPK.setText((String)TblAnggota.getValueAt(row,3));
        txtAlamat.setText((String)TblAnggota.getValueAt(row,4));
        txtxMasa.setText((String)TblAnggota.getValueAt(row,5));
        txtHP.setText((String)TblAnggota.getValueAt(row,6));
    
}
  
private void open_db()
    {
        try{
        Class.forName("com.mysql.jdbc.Driver");
        con=DriverManager.getConnection("jdbc:mysql://localhost:3306/perpustakaan","root","");
         st = con.createStatement();
         rs = st.executeQuery("select * from student");
         baca_data();
        }catch(Exception e){
        System.out.println("Error : "+e);
        }
    }
private void baca_data(){
        try{
                st=con.createStatement();
                rs=st.executeQuery("select * from student");
                ResultSetMetaData meta = rs.getMetaData();
                int col = meta.getColumnCount();
                int baris = 0;
                while(rs.next()) {
                    baris = rs.getRow();
                }
                dataTable = new Object[baris][col];
                int x = 0;
                rs.beforeFirst();
                while(rs.next()) {
                    dataTable[x][0] = rs.getString(1);
                    dataTable[x][1] = rs.getString(2);
                    dataTable[x][2] = rs.getString(3);
                    dataTable[x][3] = rs.getString(4);
                    dataTable[x][4] = rs.getString(5);
                    dataTable[x][5] = rs.getString(6);
                    dataTable[x][6] = rs.getString(7);
                    x++;
                }
                TblAnggota.setModel(new DefaultTableModel(dataTable,header));
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TblAnggota = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtNim = new javax.swing.JTextField();
        txtPK = new javax.swing.JTextField();
        txtxMasa = new javax.swing.JTextField();
        txtAlamat = new javax.swing.JTextField();
        txtHP = new javax.swing.JTextField();
        btnEdit = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TblAnggota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID_Anggota", "Nama", "NIM", "PK", "Masa Aktif", "Alamat", "No_HP"
            }
        ));
        TblAnggota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TblAnggotaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TblAnggota);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 1640, 172));

        jButton5.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 204, 255));
        jButton5.setText("Kembali");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 10, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Nama");

        jLabel3.setText("ID Anggota");

        jLabel4.setText("NIM");

        jLabel5.setText("PK");

        jLabel6.setText("Masa Aktif");

        jLabel7.setText("Alamat");

        jLabel8.setText("No HP");

        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });

        txtxMasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtxMasaActionPerformed(evt);
            }
        });

        btnEdit.setFont(new java.awt.Font("Consolas", 1, 18));
        btnEdit.setForeground(new java.awt.Color(0, 153, 255));
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnTambah.setFont(new java.awt.Font("Consolas", 1, 18));
        btnTambah.setForeground(new java.awt.Color(0, 153, 255));
        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnHapus.setFont(new java.awt.Font("Consolas", 1, 18));
        btnHapus.setForeground(new java.awt.Color(0, 153, 255));
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(41, 41, 41)
                        .addComponent(txtHP, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                        .addGap(514, 514, 514))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                        .addGap(486, 486, 486))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtAlamat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNama, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                            .addComponent(txtNim)
                            .addComponent(txtPK)
                            .addComponent(txtxMasa)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 546, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnHapus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 162, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(13, 13, 13)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(txtNim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(txtPK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(txtxMasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnEdit)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnTambah)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnHapus)))
                    .addContainerGap(86, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 197, 890, 260));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/master_manipulasi_anggota2.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_txtIDActionPerformed

private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
    if(txtNim.getText().equals("")){
    JOptionPane.showMessageDialog(this, "Data Gagal Disimpan","Informasi", JOptionPane.INFORMATION_MESSAGE);
    }else{
    studentManager stdmng = new studentManager();
    student s = new student();
    s.setID(txtID.getText());
    s.setNama(txtNama.getText());
    s.setNim(txtNim.getText());
    s.setPK(txtPK.getText());
    s.setAlamat(txtAlamat.getText());
    s.setTanggal(txtxMasa.getText());
    s.setNoHp(txtHP.getText());
    txtNim.requestFocus();
    stdmng.Insert(s);
    JOptionPane.showMessageDialog(this, "Data Berhasil Disimpan","Informasi", JOptionPane.INFORMATION_MESSAGE);
    txtID.setText("");
        txtNama.setText("");
        txtNim.setText("");
        txtPK.setText("");
        txtAlamat.setText("");
        txtxMasa.setText("");
        txtHP.setText("");     
    open_db();
     baca_data(); 
    }
}//GEN-LAST:event_btnTambahActionPerformed

private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
studentManager studentmgr = new studentManager();
    student s = new student();
    s.setNim(txtNim.getText());
    s.setID(txtID.getText());
    if(txtNim.getText().equals("") && txtID.getText().equals("")){
    JOptionPane.showMessageDialog(this, "Data Yang Anda Masukan Salah","Informasi", JOptionPane.INFORMATION_MESSAGE);
    }else{
    int dialog = JOptionPane.showConfirmDialog(this,"Apakah anda yakin data ini akan dihapus","konfirmasi", JOptionPane.YES_NO_OPTION);
    studentmgr.Delete(s);
    JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus","Informasi", JOptionPane.INFORMATION_MESSAGE);
    open_db();
     baca_data(); 
     txtID.setText("");
        txtNama.setText("");
        txtNim.setText("");
        txtPK.setText("");
        txtAlamat.setText("");
        txtxMasa.setText("");
        txtHP.setText(""); 
    // TODO add your handling code here:
}//GEN-LAST:event_btnHapusActionPerformed
}
private void TblAnggotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblAnggotaMouseClicked
// TODO add your handling code here:
    setField();
}//GEN-LAST:event_TblAnggotaMouseClicked

private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
if(btnEdit.getText().equals("Edit")){
    studentManager stdmng = new studentManager();
    student s = new student();
    s.setID(txtID.getText());
    s.setNama(txtNama.getText());
    s.setNim(txtNim.getText());
    s.setPK(txtPK.getText());
    s.setAlamat(txtAlamat.getText());
    s.setTanggal(txtxMasa.getText());
    s.setNoHp(txtHP.getText());
    btnEdit.setText("Simpan");
    btnHapus.setText("Hapus");
    }else if(txtNim.getText().equals("")){
    JOptionPane.showMessageDialog(this, "Data Gagal Disimpan","Informasi", JOptionPane.INFORMATION_MESSAGE);
    btnEdit.setText("Edit");
    }else{
    studentManager stdmng = new studentManager();
    student s = new student();
    s.setID(txtID.getText());
    s.setNama(txtNama.getText());
    s.setNim(txtNim.getText());
    s.setPK(txtPK.getText());
    s.setAlamat(txtAlamat.getText());
    s.setTanggal(txtxMasa.getText());
    s.setNoHp(txtHP.getText());
    stdmng.Update(s);
    JOptionPane.showMessageDialog(this, "Data Berhasil Disimpan","Informasi", JOptionPane.INFORMATION_MESSAGE);
    txtID.setText("");
        txtNama.setText("");
        txtNim.setText("");
        txtPK.setText("");
        txtAlamat.setText("");
        txtxMasa.setText("");
        txtHP.setText(""); 
        btnEdit.setText("Edit");
    open_db();
     baca_data(); 
    }// TODO add your handling code here:
}//GEN-LAST:event_btnEditActionPerformed

private void txtxMasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtxMasaActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_txtxMasaActionPerformed

private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
new halamanutama().setVisible(true);
dispose();// TODO add your handling code here:
}//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManipulasiAnggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManipulasiAnggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManipulasiAnggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManipulasiAnggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ManipulasiAnggota().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TblAnggota;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtHP;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNim;
    private javax.swing.JTextField txtPK;
    private javax.swing.JTextField txtxMasa;
    // End of variables declaration//GEN-END:variables
}
