package perpustakaan.admin;

import app.data.Buku;
import app.data.ConnectionUtilities;
import app.data.pinjam;
import app.data.pinjamManager;
import com.sun.crypto.provider.RSACipher;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.swing.JRViewer;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DEA
 */
public class Pengembalian extends javax.swing.JFrame {
String url="jdbc:mysql://localhost:3306/",db="Perpustakaan",driver ="com.mysql.jdbc.Driver";
Integer sisa;
Connection con;
Statement st;
ResultSet rs;
Date dt = new Date();
SimpleDateFormat df = new SimpleDateFormat("dd-MM-yyyy");
private Object[][] dataTable = null;
private String[] header = {"NIM","IDBuku","Tanggal Pinjam","Tanggal Jatuh Tempo","Tanggal Kembali","Denda"};
    /** Creates new form ManipulasiAnggota */
public Pengembalian() {
        initComponents();
        open_db();
        GregorianCalendar now = new GregorianCalendar();
        
        Calendar cal = Calendar.getInstance();
        tglkembali.setText((cal.get(Calendar.DATE)) + "-"+(cal.get(Calendar.MONTH)+1) +"-"+(cal.get(Calendar.YEAR)));
    }
    
    
    /**
     * Creates new form Cek_Anggota
     */
private void setField()
{ int row=TabelPinjam.getSelectedRow();
        txtNim.setText((String)TabelPinjam.getValueAt(row,0));
        txtIDBuku.setText((String)TabelPinjam.getValueAt(row,1));
        txtjthtempo.setText((String)TabelPinjam.getValueAt(row,3));
     
    
}
  
private void open_db()
    {
        try{
        Class.forName("com.mysql.jdbc.Driver");
        con=DriverManager.getConnection("jdbc:mysql://localhost:3306/perpustakaan","root","");
         st = con.createStatement();
         rs = st.executeQuery("select * from peminjaman");
         baca_data();
        }catch(Exception e){
        System.out.println("Error : "+e);
        }
    }
private void baca_data(){
        try{
                st=con.createStatement();
                ResultSetMetaData meta = rs.getMetaData();
                int col = meta.getColumnCount();
                int baris = 0;
                while(rs.next()) {
                    baris = rs.getRow();
                }
                dataTable = new Object[baris][col];
                int x = 0;
                rs.beforeFirst();
                while(rs.next()) {
                    dataTable[x][0] = rs.getString(1);
                    dataTable[x][1] = rs.getString(2);
                    dataTable[x][2] = rs.getString(3);
                    dataTable[x][3] = rs.getString(4);
                    dataTable[x][4] = rs.getString(5);
                    dataTable[x][5] = rs.getString(6);
                    x++;
                }
                TabelPinjam.setModel(new DefaultTableModel(dataTable,header));
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    /**
     * Creates new form Pengembalian
     */
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        txtNim = new javax.swing.JTextField();
        txtIDBuku = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelPinjam = new javax.swing.JTable();
        tglkembali = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        denda = new javax.swing.JTextField();
        txtjthtempo = new javax.swing.JTextField();
        txttelat = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtstock = new javax.swing.JTextField();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNim.setBorder(null);
        getContentPane().add(txtNim, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 190, 290, 30));

        txtIDBuku.setBorder(null);
        getContentPane().add(txtIDBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 240, 290, 30));

        btnSearch.setFont(new java.awt.Font("Consolas", 1, 18));
        btnSearch.setForeground(new java.awt.Color(0, 153, 255));
        btnSearch.setText("Cari");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 180, 100, 40));

        TabelPinjam.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TabelPinjam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Anggota", "ID Buku", "Tanggal Pinjam", "Tgl Jatuh Tempo", "Tanggal Kembali", "Denda"
            }
        ));
        TabelPinjam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelPinjamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelPinjam);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 530, 687, 114));

        tglkembali.setBorder(null);
        getContentPane().add(tglkembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 340, 290, 30));

        jButton2.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 153, 255));
        jButton2.setText("HITUNG");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 430, 110, 40));

        denda.setBorder(null);
        denda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dendaActionPerformed(evt);
            }
        });
        getContentPane().add(denda, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 440, 290, 30));

        txtjthtempo.setBorder(null);
        getContentPane().add(txtjthtempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 290, 290, 30));

        txttelat.setBorder(null);
        getContentPane().add(txttelat, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 390, 290, 30));

        jButton4.setFont(new java.awt.Font("Consolas", 1, 18));
        jButton4.setForeground(new java.awt.Color(0, 204, 255));
        jButton4.setText("Cetak Laporan");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 20, -1, -1));

        jButton5.setFont(new java.awt.Font("Consolas", 1, 18));
        jButton5.setForeground(new java.awt.Color(0, 204, 255));
        jButton5.setText("Kembali");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/master_pengembalianbuku_fix.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, -1, -1));
        getContentPane().add(txtstock, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 490, 30, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dendaActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
    if(txtNim.getText().equals(""))
    {JOptionPane.showMessageDialog(this, "Nim Kosong", "Information", JOptionPane.INFORMATION_MESSAGE);
        open_db();}else{
    try{
    st = con.createStatement();
    rs = st.executeQuery("select * from peminjaman where Nim = '"+txtNim.getText()+"'");
    baca_data();
}catch(SQLException e){
    JOptionPane.showMessageDialog(null, e);
    }
    // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchActionPerformed
    }
    private void TabelPinjamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelPinjamMouseClicked
setField();        // TODO add your handling code here:
    }//GEN-LAST:event_TabelPinjamMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
   
    Date tgl1,tgl2;
    Long lm = null;
    try{
   tgl1 = df.parse(txtjthtempo.getText());
    tgl2 = df.parse(tglkembali.getText());
    lm =  (tgl2.getTime() - tgl1.getTime()) / (24*60*60*1000);
    
    }catch (ParseException e){
        e.printStackTrace();
    }
    txttelat.setText(String.valueOf(lm));
    int telat=Integer.parseInt(txttelat.getText());
        int hasil= 500*telat;
        denda.setText("Rp. "+hasil);
    
  if((txtNim.getText().equals("")) || (txtIDBuku.getText().equals(""))){
    JOptionPane.showMessageDialog(this, "Data Gagal Disimpan","Informasi", JOptionPane.INFORMATION_MESSAGE);
    }else{
    pinjamManager pjm = new pinjamManager();
    pinjam p = new pinjam();
    p.setNim(txtNim.getText());
    p.setIDBuku(txtIDBuku.getText());
    p.setTglKembali(tglkembali.getText());
    p.setTglJatuhTempo(txtjthtempo.getText());
    p.setDenda(hasil);
   
    txtNim.requestFocus();
    txtIDBuku.requestFocus();
    pjm.Update(p);
    ConnectionUtilities.getConnection();
    try{
        con=DriverManager.getConnection(url+db,"root","");
        st=con.createStatement();
        rs=st.executeQuery("select * from buku where IDBuku='"+txtIDBuku.getText()+"'");
        ResultSetMetaData meta=rs.getMetaData();
        rs.beforeFirst();
        if(rs.next()){
            txtstock.setText(rs.getString("Stock"));
        }
        else {
           JOptionPane.showMessageDialog(this,"Gagal Ditemukan","Informasi",JOptionPane.INFORMATION_MESSAGE);
        }
    }
    catch(Exception e){
        JOptionPane.showMessageDialog(this,"ERORR DISINI "+e.getMessage(),"Informasi",JOptionPane.INFORMATION_MESSAGE);
    
    }
    sisa=Integer.valueOf(txtstock.getText())+1;
    String kode="update buku set stock='"+sisa+"' where IDBuku='"+txtIDBuku.getText()+"'"; 
    int edit;
            try {
                edit = st.executeUpdate(kode);
            } catch (SQLException ex) {
                Logger.getLogger(Peminjaman.class.getName()).log(Level.SEVERE, null, ex);
            }
    JOptionPane.showMessageDialog(this, "Data Berhasil Disimpan","Informasi", JOptionPane.INFORMATION_MESSAGE);
        txtIDBuku.setText("");
        txtNim.setText("");
        txtjthtempo.setText("");
        txttelat.setText("");
        denda.setText("");
        txtstock.setText("");
        open_db();
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
try{
        String stream = "H:/Report Perpustakaan/report1.jrxml";
        
        JasperReport jasperReport = JasperCompileManager.compileReport(stream);
        JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, null, ConnectionUtilities.getConnection());
        JRViewer aViewer = new JRViewer(jasperPrint);
        
        JDialog viewer = new JDialog();
        viewer.setTitle(".: Jasper Report :.");
        viewer.setAlwaysOnTop(true);
        viewer.getContentPane().add(aViewer);
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        viewer.setBounds(0,0,screenSize.width, screenSize.height);
        viewer.setVisible(true);
        
    }catch(JRException ex){
        Logger.getLogger(ManipulasiAnggota.class.getName()).log(Level.SEVERE, null, ex);
    }// TODO add your handling code here:
}//GEN-LAST:event_jButton4ActionPerformed

private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
new halamanutama().setVisible(true);
dispose();// TODO add your handling code here:
}//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pengembalian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelPinjam;
    private javax.swing.JButton btnSearch;
    private javax.swing.JTextField denda;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tglkembali;
    private javax.swing.JTextField txtIDBuku;
    private javax.swing.JTextField txtNim;
    private javax.swing.JTextField txtjthtempo;
    private javax.swing.JTextField txtstock;
    private javax.swing.JTextField txttelat;
    // End of variables declaration//GEN-END:variables
}
